### ISSUE TITLE
[FEATURE] Add the ability to configure the report record count limit from the UI.

### ISSUE THREAD

**Issue by ganilmca** [opensearch-project/dashboards-reporting#328]
Hi Team,

Not able to download report as saved in opensearch more than 10000 records.

Can any one please help us to download the report even we have millions of records.

Please let us know if anything required from my end.

Thanks,
Anil

**Comment by Swiddis** [comment]
This is possible in the API but not in the UI. The limit is specified by the `report_params.core_params.limit` field in the request to the Backend, so you can recreate a report with a new limit and delete the old report.

<img width="554" alt="image" src="https://github.com/opensearch-project/dashboards-reporting/assets/31739405/ab481041-fef8-4f63-8bfe-5e0633bf7965">

Marking this as a UI feature request instead of a bug. Thanks for the issue!

**Comment by Swiddis** [comment]
More steps at #60.

**Comment by Swiddis** [comment]
Going to mark this as a good first issue. The limit is set in the request in [report_settings.tsx](https://github.com/opensearch-project/dashboards-reporting/blob/2f7ae070db08efb8042792009ef577f1e5590b23/public/components/report_definitions/report_settings/report_settings.tsx#L173). The different input fields are specified [in the same file](https://github.com/opensearch-project/dashboards-reporting/blob/2f7ae070db08efb8042792009ef577f1e5590b23/public/components/report_definitions/report_settings/report_settings.tsx#L920), consider adding another input field that updates this limit. It should only be enabled for saved search types, I think?
